### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by raoulbaldwin** [amjedcha/new_banking#1]
in the menu, and click on drop, the menu closes, but the keyboard becomes innocent

**Comment by jacobwi** [comment]
The issue should be solved by the latest update. Make sure to disable any banking/atm systems.

**Comment by JaroSound** [comment]
I still have this issue... All banking/atm systems disabled.
